# -*- coding: utf-8 -*-
"""CV LAB-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJiDO7zhosYKJP4f2gEAiDxNMmREgssq
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

img=cv2.imread("/content/drive/MyDrive/Computer Vision/pngtree-new-4k-nature-cb-editing-background-image_16123064.jpg")
grayscale = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

rows, cols = grayscale.shape

output1 = np.zeros((rows-2, cols-2), dtype=np.uint8)
output2 = np.zeros((rows-4, cols-4), dtype=np.uint8)
output3 = np.zeros((rows-6, cols-6), dtype=np.uint8)

for i in range(1, rows-1):
    for j in range(1, cols-1):

        total = 0

        for x in range(-1, 2):
            for y in range(-1, 2):
                total += int(grayscale[i+x][j+y])

        output1[i-1][j-1] = total // 9

for i in range(2, rows-2):
    for j in range(2, cols-2):

        total = 0

        for x in range(-2, 3):
            for y in range(-2, 3):
                total += int(grayscale[i+x][j+y])

        output2[i-2][j-2] = total // 25

for i in range(3, rows-3):
    for j in range(3, cols-3):

        total = 0

        for x in range(-3, 4):
            for y in range(-3, 4):
                total += int(grayscale[i+x][j+y])

        output3[i-3][j-3] = total // 49


plt.figure(figsize=(10,8))

plt.subplot(2,2,1)
plt.imshow(grayscale, cmap='gray')
plt.title("Original")
plt.axis("off")

plt.subplot(2,2,2)
plt.imshow(output1, cmap='gray')
plt.title("Mean Filter (3x3)")
plt.axis("off")

plt.subplot(2,2,3)
plt.imshow(output2, cmap='gray')
plt.title("Mean Filter (5x5)")
plt.axis("off")

plt.subplot(2,2,4)
plt.imshow(output3, cmap='gray')
plt.title("Mean Filter (7x7)")
plt.axis("off")

plt.tight_layout()
plt.savefig("Output.png")
plt.show()

print("Original Image Shape :", img.shape)
print("Grayscale Shape      :", grayscale.shape)
print("3x3 Output Shape     :", output1.shape)
print("5x5 Output Shape     :", output2.shape)
print("7x7 Output Shape     :", output3.shape)

from google.colab import files
import numpy as np
import matplotlib.pyplot as plt


uploaded = files.upload()

filename = list(uploaded.keys())[0]

img = plt.imread(filename)

# Convert RGB image to grayscale
if len(img.shape) == 3:
    img = np.mean(img[:, :, :3], axis=2)

print("Image loaded successfully!")
print("Image:", filename)


def average_filter(image, size):


    pad = size // 2

    padded = np.pad(image, pad, mode='constant')

    output = np.zeros_like(image, dtype=float)

    for i in range(image.shape[0]):
        for j in range(image.shape[1]):

            window = padded[i:i+size, j:j+size]

            output[i, j] = np.mean(window)

    return output


blur_3x3 = average_filter(img, 3)
blur_5x5 = average_filter(img, 5)
blur_7x7 = average_filter(img, 7)



plt.figure(figsize=(12, 10))


plt.subplot(2, 2, 1)
plt.imshow(img, cmap='gray')
plt.title("Original Grayscale Image")
plt.axis('off')


plt.subplot(2, 2, 2)
plt.imshow(blur_3x3, cmap='gray')
plt.title("Average Filter (3x3)")
plt.axis('off')


plt.subplot(2, 2, 3)
plt.imshow(blur_5x5, cmap='gray')
plt.title("Average Filter (5x5)")
plt.axis('off')


plt.subplot(2, 2, 4)
plt.imshow(blur_7x7, cmap='gray')
plt.title("Average Filter (7x7)")
plt.axis('off')

plt.tight_layout()
plt.show()